AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'test/**/*'
    - 'bin/**/*'
    - 'lib/Gemfile.rb'

Style/Documentation:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 60

Metrics/AbcSize:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 14

Layout/LineLength:
  Max: 120

Lint/DuplicateBranch:
  Enabled: false
